/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'
import { useGSAP } from '@gsap/react'
import gsap from 'gsap'

export function Planet(props) {
    const shapeContainer = useRef(null)
    const spheresContainer = useRef(null)
    const ringContainer = useRef(null)

    const { nodes, materials } = useGLTF('/models/Planet.glb')

    useGSAP(() => {
        const tl = gsap.timeline()

        // 전체 이미지가 아래에서 위로 약간 올라옴
        tl.from(shapeContainer.current.position, {
            y: 5,
            duration: 6,
            ease: 'circ.out'
        })

        // 구체들이 회전
        tl.from(spheresContainer.current.rotation, {
            x: 0,
            y: Math.PI,
            z: -Math.PI,
            duration: 10,
            ease: 'power1.inOut'
        }, '-=25%')  // 이전 에니메이션이 끝나기 25% 전에 시작

        // 링 회전
        tl.from(ringContainer.current.rotation, {
            x: 0.8,
            y: 0,
            z: 0,
            duration: 10,
            ease: 'power1.inOut'
        }, '<')  // 동시에 시작
    }, [])

    return (
        <group {...props} dispose={null} ref={shapeContainer}>
            <group ref={spheresContainer}>
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.Sphere.geometry}
                    material={materials['Material.002']}
                    rotation={[0, 0, 0.741]}
                />
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.Sphere2.geometry}
                    material={materials['Material.001']}
                    position={[0.647, 1.03, -0.724]}
                    rotation={[0, 0, 0.741]}
                    scale={0.223}
                />
            </group>

            <mesh
                ref={ringContainer}
                castShadow
                receiveShadow
                geometry={nodes.Ring.geometry}
                material={materials['Material.001']}
                rotation={[-0.124, 0.123, -0.778]}
                scale={2}
            />

        </group>
    )
}

useGLTF.preload('/models/Planet.glb')
